### ISSUE TITLE
防撤回，如若撤回的是图片信息，则无法加载

### ISSUE THREAD

**Issue by ElieenAndBella** [BetterNCM/UwU#45]
具体表现：
![image](https://github.com/BetterQQNT/BetterQQNT/assets/54427695/c1ec052d-3ce4-47a8-97af-39949abcfbab)
相关信息：
平台：Windows 11 x64
QQ版本：9.9.0

**Comment by ElieenAndBella** [comment]
9.9.0 - 14619

**Comment by pommeJack** [comment]
+1

**Comment by pommeJack** [comment]
只有在主面板没有打开的时候出现，猜测是因为QQ在后台时不会主动加载图片。

**Comment by MicroCBer** [comment]
现在并没有自动下载所有图片（避免浪费储存空间）

**Comment by pommeJack** [comment]
> 现在并没有自动下载所有图片（避免浪费储存空间）

后续会实现“自动下载所有图片”吗？

**Comment by MengNianxiaoyao** [comment]
自动下载所有图片很浪费空间，但好像图片都有缓存在本地，当图片被撤回，调用缓存读取应该能行
